networks:
  kafka-net:
    name: kafka-net
    driver: bridge
  agronetwork:
    name: agronetwork
    driver: bridge

services:
  ndvi-worker:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ndvi-worker
    env_file:
      - .env
    networks:
      - kafka-net
      - agronetwork
    mem_limit: 2048m
